[package]
name = "soroban"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
tracing = { workspace = true }

config.workspace = true
async-trait.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
stellar-rpc-client.workspace = true
stellar-xdr.workspace = true
stellar-strkey.workspace = true
jsonrpsee-core.workspace = true
jsonrpsee-http-client.workspace = true
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread", "sync"] }
url.workspace = true

[dev-dependencies]
axum.workspace = true
