[package]
name = "worker"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
config = { workspace = true }
telemetry = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "time"] }
tracing = { workspace = true }
